export const DashboardType = {
  GET_DEPARTMENT: 'GET_DEPARTMENT',
  SET_EMPLOYEE_FIELD: 'SET_EMPLOYEE_FIELD',
  GET_EMP_ID: 'GET_EMP_ID',
  GET_EMP_DETAIL: 'GET_EMP_DETAIL',
  GET_EMP_DETAIL_FAILED: 'GET_EMP_DETAIL_FAILED',
  CLEAR_EMP_DATA: 'CLEAR_EMP_DATA'
};

export const LoginType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SET_LOGIN_TEXT_FIELD: 'SET_LOGIN_TEXT_FIELD'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};
